name: cs design
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#464646'
    - '#a8a8a8'
    - '#00ff01'
    - '#8b8b8b'
  brandStrength: 0.6447958413045853
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
